#+TITLE: Machine learning optimized numerical wave flume
#+OPTIONS: toc:nil
#+AUTHOR: Zhouteng Ye

As my personal knowledge, numerical wave flumes for coastal/ocean engineering in
the world now are always facing the problem: efficiency and resolution. Simple
algorithms are efficient, but the resolution is low; High resolution algorithms
are time-consuming and complex. It usually takes very long time to get a
satisfying results.

Machine leaning has a huge potential to help improving numerical wave flume. It
can help accelerating the numerical simulation and also help improving the
numerical results. 

* Reasons that I choose this topic

- Machine learning can help acceleration of the iterations in the CFD model, e.g.
  Poisson solver in projection method, reconstruction of MOF.
- Machine learning can help maintaining high resolution using simple algorithm
  or us less grid.
- Machine learning can help determine the parameters in numerical simulation,
  e.g. parameters for RANS, LES, parameters for sediment transportation.
- I am more familiar with the engineering background in ocean engineering than
  other topics.
- I am planning to apply a new Ph.D. program other than ocean engineering, but I
  am going to enroll the new program in 2019, there was still a long before
  enrolling the new program. In the mean time, I will not give up on my degree
  in China, doing something related with ocean engineering could also help 

* Short-term plan (from now to December 1, 2018)

- Acceleration of MOF construction using machine learning

* Long-term plan (if I can get extended to December 1, 2019)

- Numerical flume that can deal with wave propagation, shoaling, breaking and
  interaction with sediment transport and structures.
- Data Driven projection method for multi-phase flow
- An algorithm that uses the fine grid results as training data that could
  applied to correct the coarse grid simulation. It can also use experimental
  data as training data to help improving the numerical results.
